services:
  loan-application:
    build: .
    container_name: loan-application
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    depends_on:
      - pg
  pg:
    image: postgres:16.2-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/posgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - pg

volumes:
  pgdata:


docker run -d --name postgres-container -p 5432:5432 -e POSTGRES_PASSWORD=admin-postgres 8b569a69e22b